"""empty message

Revision ID: 5179b1385fc1
Revises: 407d067b58d2
Create Date: 2023-01-29 16:41:49.869298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5179b1385fc1'
down_revision = '407d067b58d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor', sa.String(), nullable=True))

    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_column('rating')

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('actor')

    # ### end Alembic commands ###
